services:
  sniffer:
    build: ./go-sniffer
    container_name: packet_sniffer_go
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      db:
        condition: service_healthy

  db:
    image: timescale/timescaledb:latest-pg16
    container_name: timescale_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d packets"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  ui:
    build: ./python-ui
    container_name: packet_ui_python
    restart: unless-stopped
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: